# Generated by Django 3.0.5 on 2020-04-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_invite_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='design_paper',
            field=models.CharField(choices=[('minions.jpg', 'minions')], max_length=100, null=True),
        ),
    ]
