# Generated by Django 3.0.5 on 2020-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_invite_design_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='contact_phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='event_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
